#!/usr/bin/env bash

port=$1

if [ -z "$port" ]; then
  echo "Usage: kill-port <port>"
  exit 1
fi

pid=$(lsof -t -i:$port)

if [ -n "$pid" ]; then
  echo "Port $port is busy by PID $pid"
  kill -9 $pid
  echo "Process $pid killed"
else
  echo "Port $port is free"
fi
