#!/usr/bin/env bash

mode="$1"
message="$2"

if [ -z "$mode" ]; then
  echo "Usage: $(basename $0) <major|minor|patch> [message]"
  exit 1
fi

if [ -n "$message" ]; then
  git add .
  git commit -am "$message"
fi

git push
npm ci
npm run build --if-present
npm version $mode
npm publish
git sync
