#!/usr/bin/env bash

mode="$1"
message="$2"

if [ -z "$mode" ]; then
  echo "Usage: $(basename $0) <major|minor|patch> [message]"
  exit 1
fi

if [ -n "$message" ]; then
  __print_command_and_eval "git add ."
  __print_command_and_eval "git commit -am "$message""
fi

__print_command_and_eval "git push"
__print_command_and_eval "npm ci"
__print_command_and_eval "npm run build --if-present"
__print_command_and_eval "npm version $mode"
__print_command_and_eval "npm publish"
__print_command_and_eval "git sync"
