#!/usr/bin/env bash

mode="$1"
message="$2"

usage="Usage: npm-release-package <major|minor|patch> [message]"

if [ -z "$mode" ]; then
  echo "$usage"
  exit 1
fi

if [ -n "$message" ]; then
  git add .
  git commit -am "$message"
fi

git push
npm ci
npm run build --if-present
npm version $mode
npm publish
git sync
