#!/usr/bin/env bash

times=$1
command=$2

if [ -z "$command" ]; then
  echo "Usage: $(basename $0) <times> <command>"
  exit 1
fi

echo "Running $times times a command: $command"

for i in $(seq 1 $times)
do
  eval "$command"
done
