#!/usr/bin/env bash

command="${1}"

if [ -z "$command" ]; then
  echo "Usage: run-on-each-dir \"<command>\""
  exit 1
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/__colors.sh"

for d in ./*/
do
  if [ -d "$d" ]; then
    cd "$d"
    echo -n "==> "
    __set_color "${__COLOR_GREEN}"
    echo -n "$d"
    __set_color "${__COLOR_BLUE}"
    echo -n " > "
    __set_color "${__COLOR_RESET}"
    echo -e "$command"
    eval "$command"
    cd ".."
    echo ""
  fi
done
