#!/usr/bin/env bash

name=$(basename "$(pwd)")

read -p "Are you sure you want to delete "$name" directory? [y/N]: " choice

case $choice in
  [yY])
    cd ..
    rm -rf "$name"
    echo "[+] Directory \"$name\" was removed successfully!"
    echo -e "\nWARNING: Remember to change directory!"
    ;;
  *)
    echo "ERROR: Process was canceled"
    ;;
esac
